---
version: "2.0"

create_volume_backup:
  type: direct

  input:
    - volume_id
    - force: True
    - incremental: True
    - description: "Created by mistral"

  description: create a backup for a volume.

  tasks:
    create_backup:
      description: create a backup for a volume
      action: cinder.backups_create volume_id=<% $.volume_id %> force=<% $.force %> incremental=<% $.incremental %> description=<% $.description %>
      publish:
        backup_id: <% task(create_backup).result.id %>
      on-success:
        - wait_for_active

    wait_for_active:
      action: cinder.backups_find id=<% $.backup_id %> status='available'
      retry:
        delay: 10
        count: 30
