{
 "title": "Libvirt",
 "description": "This is complete dashboard to monitor libvirt hypervisors and virtual machines",
 "tags": [
  "libvirt",
  "instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(libvirt_up, instance)"
    }
   },
   {
    "name": "domain",
    "query": {
     "query": "label_values(libvirt_domain_info_vstate{instance=~\"$instance.*\"}, domain)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "query_result(label_replace(libvirt_domain_memory_stats_available, \"service\", \"$1\", \"domain\", \"([a-zA-Z-]*)[0-9]*\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RAM and Disk usage on vm",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_available{instance=~\"$instance.*\"}",
     "legendFormat": "total"
    },
    {
     "expr": "(libvirt_domain_memory_stats_used_percent{instance=~\"$instance.*\"} * libvirt_domain_memory_stats_available{instance=~\"$instance.*\"}) / 100",
     "legendFormat": "used"
    },
    {
     "expr": "libvirt_domain_memory_stats_used_percent{instance=~\"$instance.*\"}",
     "legendFormat": "used %"
    },
    {
     "expr": "libvirt_domain_block_stats_physicalsize{instance=~\"$instance.*\"}",
     "legendFormat": "Disk Size"
    }
   ]
  },
  {
   "title": "CPU load on VM",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_info_cpu_time_seconds_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m]) * 100\n",
     "legendFormat": "VM CPU load"
    }
   ]
  },
  {
   "title": "Memory used percent",
   "type": "graph",
   "description": "The amount of memory in percent, that used by domain.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_used_percent{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Memory Stats (by instance and domain)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available memory inside vm",
   "type": "graph",
   "description": "How much the balloon can be inflated without pushing the guest system to swap, corresponds to 'Available' in /proc/meminfo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_usable{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Total memory inside vm",
   "type": "graph",
   "description": "The total amount of usable memory as seen by the domain. This value may be less than the amount of memory assigned to the domain if a balloon driver is in use or if the guest OS does not initialize all assigned pages. This value is expressed in kB.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_available{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Current balloon value",
   "type": "graph",
   "description": "Current balloon value (in KB).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_actual_balloon{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Completely unused memory",
   "type": "graph",
   "description": "The amount of memory left completely unused by the system. Memory that is available but used for reclaimable caches should NOT be reported as free. This value is expressed in kB.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_unused{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "description": "The amount of memory, that can be quickly reclaimed without additional I/O (in kB).Typically these pages are used for caching files from disk.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_disk_cache{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Interface Stats (by instance and domain)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "description": "Number of bytes transmitted on a network interface, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_interface_stats_transmit_bytes_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
     "legendFormat": "{{domain}} - transmit"
    },
    {
     "expr": "irate(libvirt_domain_interface_stats_receive_bytes_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
     "legendFormat": "{{ domain }} - receive"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "description": "Number of packets received on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_packets_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
     "legendFormat": "{{domain}} - receive"
    },
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_packets_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
     "legendFormat": "{{domain}} - transfer"
    }
   ]
  },
  {
   "title": "Network traffic transmits total",
   "type": "graph",
   "description": "Number of bytes transmitted on a network interface, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_interface_stats_transmit_bytes_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{ domain }} - {{ instance }} total"
    }
   ]
  },
  {
   "title": "Network traffic receives total",
   "type": "graph",
   "description": "Number of bytes transmitted on a network interface, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_interface_stats_receive_bytes_total{ domain=~\"$domain.*\"}",
     "legendFormat": "{{ domain }} - {{ instance }}receive total"
    }
   ]
  },
  {
   "title": "Domain Info (by instance and domain)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virsh defined memory bytes",
   "type": "graph",
   "description": "Maximum allowed memory of the domain, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "description": " Memory usage of the domain, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_info_memory_usage_bytes{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "VCPU count",
   "type": "stat",
   "description": "Number of virtual CPUs for the domain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "VM state",
   "type": "graph",
   "description": "Virtual domain state. 0: no state, 1: the domain is running, 2: the domain is blocked on resource, 3: the domain is paused by user, 4: the domain is being shut down, 5: the domain is shut off,6: the domain is crashed, 7: the domain is suspended by guest power management",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_info_vstate{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Block Stats (by instance and domain)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Write and read requests",
   "type": "graph",
   "description": "Number of write requests to a block device.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_write_requests_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
     "legendFormat": "{{domain}} - write"
    },
    {
     "expr": "irate(libvirt_domain_block_stats_read_requests_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
     "legendFormat": "{{domain}} - read"
    }
   ]
  },
  {
   "title": "Flush requests",
   "type": "graph",
   "description": "Total flush requests from a block device.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_flush_requests_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Write and read bytes",
   "type": "graph",
   "description": "Number of bytes written to a block device, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_write_bytes_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
     "legendFormat": "{{domain}} - write"
    },
    {
     "expr": "irate(libvirt_domain_block_stats_read_bytes_total{instance=~\"$instance.*\", domain=~\"$domain.*\"}[5m])",
     "legendFormat": "{{ domain }} - read"
    }
   ]
  },
  {
   "title": "Image allocation",
   "type": "graph",
   "description": "Offset of the highest written sector on a block device.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_block_stats_allocation{instance=~\"$instance.*\", domain=~\"$domain.*\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}